// This file is auto-generated by @hey-api/openapi-ts

export type RegisterUserDto = {
    email: string;
    password: string;
    phone: string;
    full_name: string;
};

export type GetSmsTimerResponse = {
    readonly expiresIn: number;
    readonly message: string;
};

export type SendSmsDto = {
    phone: string;
};

export type AuthResponse = {
    readonly access_token: string;
    readonly refresh_token: string;
};

export type VerifyCodeDto = {
    phone: string;
    code: string;
};

export type Role = 'user' | 'seller';

export type UserEntityWithoutPassword = {
    role: Role;
    id: number;
    full_name: string;
    email: string;
    phone: string;
    photo: string | null;
    shop?: {
        [key: string]: unknown;
    };
    companies?: {
        [key: string]: unknown;
    };
};

export type UsersPatchDto = {
    role: Role;
    photo: string;
    email: string;
    phone: string;
    full_name: string;
};

export type type = 'INDIVIDUAL' | 'LEGAL';

export type taxation = 'IE_without_VAT' | 'IE_with_VAT' | 'IE_Professional_Income_Tax' | 'self_employed' | 'company_with_VAT' | 'company_without_VAT';

export type CompaniesDto = {
    type: type;
    taxation: taxation;
    name: string;
    itn: number;
    psrnsp: number;
    kpp: number;
};

export type CompaniesResponse = {
    id: number;
    name: string;
    itn: number;
    psrnsp: number;
    kpp: number;
    type: type;
    taxation: taxation;
};

export type rate = 'low' | 'medium' | 'hight';

export type ShopEntity = {
    rate: rate;
    address: string;
    description: string;
    id: number;
    logo: string;
    name: string;
    company: {
        id: number;
        name: string;
    };
};

export type ShopEntityMinInfo = {
    rate: rate;
    address: string;
    logo: string;
    name: string;
    description: string;
    id: number;
};

export type CreateShopDto = {
    rate: rate;
    name: string;
    description?: string;
    address: string;
    logo?: string;
};

export type UpdateShopDto = {
    name: string;
    description?: string;
    address: string;
    logo?: string;
};

export type SubCategoryMinResponse = {
    id: number;
    name: string;
    seo: string;
};

export type CategoryResponse = {
    name: string;
    logo: string;
    seo: string;
    isPopular: boolean;
    id: number;
    parentId?: number;
    subCategories: Array<SubCategoryMinResponse>;
};

export type PopularCategoriesResponse = {
    name: string;
    logo: string;
    seo: string;
    id: number;
};

export type CreateCategoryDto = {
    name: string;
    seo: string;
};

export type FieldsSchemaDto = {
    properties: {
        [key: string]: {
            type?: string;
            enum?: Array<(string)> | null;
        };
    };
    required: Array<(string)>;
};

export type CreateSubCategoryDto = {
    fieldsSchema?: FieldsSchemaDto;
    name: string;
    excelTemplatePath: string;
    seo: string;
};

export type SubCategoryResponse = {
    parentId: number;
    id: number;
    name: string;
    excelTemplatePath: string;
    fieldsSchema: Array<(string)>;
    seo: string;
};

export type CreateItemDto = {
    name: string;
    fields: {
        [key: string]: unknown;
    };
    countryOfOrigin: string;
    article: number;
    brand: string;
    box: Array<{
        [key: string]: unknown;
    }>;
    price: number;
    sellerArticle: string;
    images: Array<(string)>;
};

export type BasketOptions = {
    [key: string]: unknown;
};

export type ItemsEntityMinInfo = {
    description: string;
    countryOfOrigin: string;
    basketOptions: Array<BasketOptions>;
    article: number;
    cardId: number;
    id: number;
    name: string;
    images: Array<(string)>;
    createdAt: string;
};

export type UpdateItemDto = {
    description: string;
    basketOptions: Array<{
        [key: string]: unknown;
    }>;
    seo: string;
    name: string;
    fields: {
        [key: string]: unknown;
    };
    countryOfOrigin: string;
    article: number;
    brand: string;
    box: Array<{
        [key: string]: unknown;
    }>;
    images: Array<(string)>;
};

export type SuggestionType = 'card' | 'category' | 'subCategory' | 'shop';

export type SearchEntityResponse = {
    id: number;
    name: string;
    suggestionType: SuggestionType;
};

export type OrganizationResponse = {
    type: type;
    name: string;
    itn: string;
    psrn: string;
    kpp: string | null;
};

export type BoxResponseDto = {
    type: 'box_single' | 'box_characteristics';
    /**
     * Опции коробки, структура зависит от типа box
     */
    options: {
    name?: string;
    quantity?: string;
} | {
    name?: string;
    fields?: Array<{
        name?: string;
        quantity?: string;
    }>;
};
};

export type type2 = 'box_single' | 'box_characteristics';

export type CardItemResponse = {
    id: string;
    name: string;
    description: string;
    images: Array<(string)>;
    countryOfOrigin: string;
    article: number;
    brand: string;
    box: (BoxResponseDto) | null;
    price: number;
    rating: number;
};

export type CardShopResponse = {
    id: string;
    name: string;
};

export type CardResponse = {
    id: number;
    preview: CardItemResponse;
    shop: CardShopResponse;
    isFavorite: boolean;
};

export type CreateBrandDto = {
    name: string;
};

export type BannerEntities = {
    id: number;
    imagePath: string;
    routePath: string;
    seo: string;
};

export type RegisterSmsData = {
    requestBody: RegisterUserDto;
};

export type RegisterSmsResponse = GetSmsTimerResponse | {
    [key: string]: unknown;
};

export type LoginSmsData = {
    requestBody: SendSmsDto;
};

export type LoginSmsResponse = GetSmsTimerResponse | {
    [key: string]: unknown;
};

export type GetSmsTimerData = {
    phone: string;
};

export type GetSmsTimerResponse2 = GetSmsTimerResponse;

export type VerifyCodeData = {
    requestBody: VerifyCodeDto;
};

export type VerifyCodeResponse = {
    access_token?: string;
    refresh_token?: string;
} | AuthResponse;

export type RefreshTokenResponse = AuthResponse;

export type LogoutResponse = unknown;

export type FindAllResponse = unknown;

export type ChangeUserRoleData = {
    requestBody: UsersPatchDto;
};

export type ChangeUserRoleResponse = UserEntityWithoutPassword;

export type GetMeResponse = UserEntityWithoutPassword;

export type GetByIdData = {
    id: number;
};

export type GetByIdResponse = UserEntityWithoutPassword;

export type CreateData = {
    requestBody: CompaniesDto;
};

export type CreateResponse = unknown;

export type GetAllCompaniesResponse = CompaniesResponse;

export type DeleteMyCompanyResponse = CompaniesResponse;

export type GetMyCompanyResponse = CompaniesResponse;

export type GetFiltersBySubCategoryIdData = {
    subCategoryId: number;
};

export type GetFiltersBySubCategoryIdResponse = unknown;

export type GetMyShopResponse = ShopEntity;

export type GetAllShopsResponse = Array<ShopEntityMinInfo>;

export type CreateShopData = {
    requestBody: CreateShopDto;
};

export type CreateShopResponse = unknown;

export type UpdateShopData = {
    requestBody: UpdateShopDto;
};

export type UpdateShopResponse = unknown;

export type GetAllCategoriesData = {
    isPopular?: boolean;
};

export type GetAllCategoriesResponse = Array<CategoryResponse>;

export type CreateCategoryData = {
    requestBody: CreateCategoryDto;
};

export type CreateCategoryResponse = unknown;

export type DeleteAllCategoriesResponse = {
    [key: string]: unknown;
};

export type GetPopularCategoriesResponse = Array<PopularCategoriesResponse>;

export type CreateSubCategoryData = {
    parentId: number;
    requestBody: CreateSubCategoryDto;
};

export type CreateSubCategoryResponse = SubCategoryResponse;

export type GetSubCategoryByIdData = {
    id: number;
};

export type GetSubCategoryByIdResponse = SubCategoryResponse;

export type DeleteCategoryByIdData = {
    id: number;
};

export type DeleteCategoryByIdResponse = unknown;

export type CreateItemData = {
    brandId: number;
    cardId: number;
    requestBody: CreateItemDto;
    subCategoryId: number;
};

export type CreateItemResponse = unknown;

export type GetAllItemsResponse = Array<ItemsEntityMinInfo>;

export type UpdateItemData = {
    id: number;
    requestBody: UpdateItemDto;
};

export type UpdateItemResponse = ItemsEntityMinInfo;

export type DeleteByIdData = {
    id: number;
};

export type DeleteByIdResponse = unknown;

export type UploadItemsImagesData = {
    formData: {
        images?: Array<((Blob | File))>;
    };
};

export type UploadItemsImagesResponse = unknown;

export type UploadBannerData = {
    formData: {
        file?: (Blob | File);
    };
};

export type UploadBannerResponse = unknown;

export type UploadShopImagesData = {
    formData: {
        image?: (Blob | File);
    };
};

export type UploadShopImagesResponse = unknown;

export type UploadItemsexcelData = {
    formData: {
        file?: (Blob | File);
    };
    subCategoryId: number;
};

export type UploadItemsexcelResponse = unknown;

export type SearchData = {
    query?: string;
};

export type SearchResponse = Array<SearchEntityResponse>;

export type GetMyBasketResponse = {
    [key: string]: unknown;
};

export type GetTotalItemsInBasketResponse = number;

export type AddItemToBasketData = {
    itemId: number;
};

export type AddItemToBasketResponse = {
    [key: string]: unknown;
};

export type GetPartyData = {
    inn: string;
};

export type GetPartyResponse = Array<OrganizationResponse>;

export type GetAllCardsData = {
    q?: string;
};

export type GetAllCardsResponse = Array<CardResponse>;

export type CreateBrandData = {
    requestBody: CreateBrandDto;
};

export type CreateBrandResponse = unknown;

export type GetBrandsResponse = unknown;

export type DeleteBrandResponse = unknown;

export type GetBrandByIdData = {
    id: number;
};

export type GetBrandByIdResponse = unknown;

export type GetCityByCoordinatesData = {
    lat: number;
    lon: number;
};

export type GetCityByCoordinatesResponse = string;

export type GetBannersResponse = Array<BannerEntities>;

export type GetFavoritesResponse = unknown;

export type ChangeFavoriteData = {
    cardId: number;
};

export type ChangeFavoriteResponse = unknown;

export type $OpenApiTs = {
    '/auth/register-sms': {
        post: {
            req: RegisterSmsData;
            res: {
                200: GetSmsTimerResponse;
                201: {
                    [key: string]: unknown;
                };
            };
        };
    };
    '/auth/login-sms': {
        post: {
            req: LoginSmsData;
            res: {
                200: GetSmsTimerResponse;
                201: {
                    [key: string]: unknown;
                };
            };
        };
    };
    '/auth/get-sms-timer': {
        get: {
            req: GetSmsTimerData;
            res: {
                200: GetSmsTimerResponse;
            };
        };
    };
    '/auth/verify-code': {
        post: {
            req: VerifyCodeData;
            res: {
                200: {
                    access_token?: string;
                    refresh_token?: string;
                };
                201: AuthResponse;
            };
        };
    };
    '/auth/refresh': {
        post: {
            res: {
                200: AuthResponse;
                201: AuthResponse;
            };
        };
    };
    '/auth/logout': {
        post: {
            res: {
                201: unknown;
            };
        };
    };
    '/users': {
        get: {
            res: {
                200: unknown;
            };
        };
        patch: {
            req: ChangeUserRoleData;
            res: {
                200: UserEntityWithoutPassword;
            };
        };
    };
    '/users/me': {
        get: {
            res: {
                200: UserEntityWithoutPassword;
            };
        };
    };
    '/users/{id}': {
        get: {
            req: GetByIdData;
            res: {
                200: UserEntityWithoutPassword;
            };
        };
    };
    '/companies': {
        post: {
            req: CreateData;
            res: {
                201: unknown;
            };
        };
        get: {
            res: {
                200: CompaniesResponse;
            };
        };
        delete: {
            res: {
                200: CompaniesResponse;
            };
        };
    };
    '/companies/my': {
        get: {
            res: {
                200: CompaniesResponse;
            };
        };
    };
    '/filters/{subCategoryId}': {
        get: {
            req: GetFiltersBySubCategoryIdData;
            res: {
                200: unknown;
            };
        };
    };
    '/shops/my': {
        get: {
            res: {
                200: ShopEntity;
            };
        };
    };
    '/shops': {
        get: {
            res: {
                200: Array<ShopEntityMinInfo>;
            };
        };
        post: {
            req: CreateShopData;
            res: {
                201: unknown;
            };
        };
        patch: {
            req: UpdateShopData;
            res: {
                200: unknown;
            };
        };
    };
    '/categories': {
        get: {
            req: GetAllCategoriesData;
            res: {
                200: Array<CategoryResponse>;
            };
        };
        post: {
            req: CreateCategoryData;
            res: {
                201: unknown;
            };
        };
        delete: {
            res: {
                200: {
                    [key: string]: unknown;
                };
            };
        };
    };
    '/categories/popular': {
        get: {
            res: {
                200: Array<PopularCategoriesResponse>;
            };
        };
    };
    '/categories/sub': {
        post: {
            req: CreateSubCategoryData;
            res: {
                201: SubCategoryResponse;
            };
        };
    };
    '/categories/sub/{id}': {
        get: {
            req: GetSubCategoryByIdData;
            res: {
                200: SubCategoryResponse;
            };
        };
    };
    '/categories/{id}': {
        delete: {
            req: DeleteCategoryByIdData;
            res: {
                200: unknown;
            };
        };
    };
    '/items': {
        post: {
            req: CreateItemData;
            res: {
                201: unknown;
            };
        };
        get: {
            res: {
                200: Array<ItemsEntityMinInfo>;
            };
        };
    };
    '/items/{id}': {
        patch: {
            req: UpdateItemData;
            res: {
                200: ItemsEntityMinInfo;
            };
        };
        get: {
            res: {
                200: unknown;
            };
        };
        delete: {
            req: DeleteByIdData;
            res: {
                200: unknown;
            };
        };
    };
    '/file-upload/items': {
        post: {
            req: UploadItemsImagesData;
            res: {
                201: unknown;
            };
        };
    };
    '/file-upload/banners': {
        post: {
            req: UploadBannerData;
            res: {
                201: unknown;
            };
        };
    };
    '/file-upload/shops': {
        post: {
            req: UploadShopImagesData;
            res: {
                201: unknown;
            };
        };
    };
    '/file-upload/excel': {
        post: {
            req: UploadItemsexcelData;
            res: {
                201: unknown;
            };
        };
    };
    '/search/{query}': {
        get: {
            req: SearchData;
            res: {
                200: Array<SearchEntityResponse>;
            };
        };
    };
    '/basket': {
        get: {
            res: {
                200: {
                    [key: string]: unknown;
                };
            };
        };
    };
    '/basket/total': {
        get: {
            res: {
                200: number;
            };
        };
    };
    '/basket/{item_id}': {
        post: {
            req: AddItemToBasketData;
            res: {
                201: {
                    [key: string]: unknown;
                };
            };
        };
    };
    '/da-data/{inn}': {
        get: {
            req: GetPartyData;
            res: {
                200: Array<OrganizationResponse>;
            };
        };
    };
    '/cards': {
        get: {
            req: GetAllCardsData;
            res: {
                200: Array<CardResponse>;
            };
        };
    };
    '/brands': {
        post: {
            req: CreateBrandData;
            res: {
                201: unknown;
            };
        };
        get: {
            res: {
                200: unknown;
            };
        };
    };
    '/brands/{id}': {
        delete: {
            res: {
                200: unknown;
            };
        };
        get: {
            req: GetBrandByIdData;
            res: {
                200: unknown;
            };
        };
    };
    '/geolocation/{lat}/{lon}': {
        get: {
            req: GetCityByCoordinatesData;
            res: {
                200: string;
            };
        };
    };
    '/banners': {
        get: {
            res: {
                200: Array<BannerEntities>;
            };
        };
    };
    '/favorites': {
        get: {
            res: {
                200: unknown;
            };
        };
    };
    '/favorites/{cardId}': {
        post: {
            req: ChangeFavoriteData;
            res: {
                201: unknown;
            };
        };
    };
};